Add project specific permissions
singhabahu/serverless-backend pull request #19
Opened 2018-06-05 14:35 UTC by singhabahu

join table `users_projects` now has a new `permission` field to manage project specific permissions. We can include permissions as a JSON string. This will follow the same pattern as the organization level permissions for the consistency.

2018-06-06 08:35 UTC, Rishanthakumar requested changes

2018-06-06 08:35 UTC, Rishanthakumar commented on src/db/models/project.js
> +    permission: Sequelize.TEXT('long'),
@singhabahu can't we use type: Sequelize.JSON ? like what we did for role permission. If you are going to use just an array this is okay.

2018-06-06 08:35 UTC, Rishanthakumar commented on src/util/permission.js
> +      include: [{
@singhabahu don't we need to get the userProject joining table permission here ?

2018-06-07 06:21 UTC, singhabahu commented
@Rishanthakumar I tried to change the TEXT feild to JSON in the DB model but it adds lot of code overhead. We'll do that later. Let's keep this simple for now.

2018-06-07 16:44 UTC, Rishanthakumar approved these changes
Looks good.

2018-06-07 16:44 UTC, merged